version: '3.1'

services:
  db-scrap:
    image: mysql:8.0.31
    container_name: mysql-scrap
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_donations
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes: 
      - mysql-data-scrap:/var/lib/mysql

volumes:
  mysql-data-scrap:
