version: '3.1'

services:
  db:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_donations
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    image: pedro6571/fatec-tg-api-donations-points:latest
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=8080
      - PROFILE=dev
    restart: always
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      retries: 5
      timeout: 10s

  scrap:
    image: pedro6571/fatec-tg-api-donations-scrap:latest
    container_name: scraping
    depends_on:
      api:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=app
      - DB_PASSWORD=app
      - DB_NAME=db_donations
      - MAPS_API_KEY=coloque aqui sua chave de API do Google Maps
      - ENVIRONMENT=local
      - ADDRESS_API_URL=http://api:8080/api
